blank_issues_enabled: false
contact_links:
  - name: ğŸ“– - Jupyter Docker Stacks documentation
    url: https://jupyter-docker-stacks.readthedocs.io/en/latest/index.html
    about: Go to the project's documentation
  - name: ğŸ” - Troubleshooting common problems
    url: https://jupyter-docker-stacks.readthedocs.io/en/latest/using/troubleshooting.html
    about: Documentation section on troubleshooting commonly encountered errors
  - name: ğŸ’¬ - Jupyter community Discourse
    url: https://discourse.jupyter.org/
    about: Interact with the rest of the Jupyter community
