name: Download build manifests from GitHub artifacts and push them to GitHub wiki
# We're doing everything in one workflow on purpose
# This way we make sure we don't access wiki pages from several jobs simultaneously

on:
  workflow_call:

jobs:
  wiki-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo âš¡ï¸
        uses: actions/checkout@v4
      - name: Create dev environment ğŸ“¦
        uses: ./.github/actions/create-dev-env
        with:
          platform: x86_64

      - name: Download all manifests and history lines ğŸ“¥
        uses: ./.github/actions/download-manifests
        with:
          histLineDir: /tmp/jupyter/hist_lines/
          manifestDir: /tmp/jupyter/manifests/
      - name: Display structure of downloaded files ğŸ”ï¸
        run: |
          ls -R /tmp/jupyter/hist_lines/
          ls -R /tmp/jupyter/manifests/
        shell: bash

      - name: Checkout Wiki Repo ğŸ“ƒ
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}.wiki
          path: wiki/

      - name: Update wiki page ğŸ·
        run: python3 -m tagging.update_wiki_page --wiki-dir wiki/ --hist-line-dir /tmp/jupyter/hist_lines/ --manifest-dir /tmp/jupyter/manifests/
        shell: bash

      - name: Push Wiki to GitHub ğŸ“¤
        if: github.repository == 'jupyter/docker-stacks' && (github.ref == 'refs/heads/main' || github.event_name == 'schedule')
        uses: stefanzweifel/git-auto-commit-action@3ea6ae190baf489ba007f7c92608f33ce20ef04a # v4.16.0
        with:
          commit_message: "Automated wiki publish for ${{ github.sha }}"
          repository: wiki/
