name: Download manifest artifacts from GitHub, tag and push to DockerHub
# We're doing everything in one workflow on purpose
# This way we make sure we don't access wiki pages from several jobs simultaneously

on:
  workflow_call:

jobs:
  tag-push:
    runs-on: ${{ inputs.runsOn }}

    strategy:
      matrix:
        image: ${{ fromJson(inputs.images) }}

    steps:
      - name: Checkout Repo âš¡ï¸
        uses: actions/checkout@v3
      - name: Create dev environment ğŸ“¦
        uses: ./.github/actions/create-dev-env

      # To make this workflow easier to implement, we download all artifacts
      # https://github.com/actions/download-artifact/issues/6
      - name: Download all artifacts ğŸ“¥
        uses: actions/download-artifact@v3
        with:
          path: /tmp/artifacts/
      - name: Display structure of downloaded files
        run: ls - R
        working-directory: /tmp/artifacts/
        shell: bash

      - name: Checkout Wiki Repo ğŸ“ƒ
        uses: actions/checkout@v3
        with:
          repository: ${{github.repository}}.wiki
          path: wiki/

      - name: Update wiki page ğŸ·
        run: python3 -m tests.update_wiki_page --wiki-dir wiki/ --artifacts-dir /tmp/artifacts/
        shell: bash

      - name: Push Wiki to GitHub ğŸ“¤
        if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main' || github.event_name == 'schedule'
        uses: stefanzweifel/git-auto-commit-action@5804e42f86b1891093b151b6c4e78e759c746c4d # dependabot updates to latest release
        with:
          commit_message: "Automated wiki publish for ${{github.sha}}"
          repository: wiki/
