name: Download build manifests from GitHub artifacts and push them to GitHub wiki
# We're doing everything in one workflow on purpose
# This way we make sure we don't access wiki pages from several jobs simultaneously

env:
  PUSH_TO_REGISTRY: ${{ (github.repository_owner == 'jupyter' || github.repository_owner == 'mathbunnyru') && (github.ref == 'refs/heads/main' || github.event_name == 'schedule') }}

on:
  workflow_call:

jobs:
  wiki-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo âš¡ï¸
        uses: actions/checkout@v4
      - name: Create dev environment ğŸ“¦
        uses: ./.github/actions/create-dev-env

      - name: Download all manifests and history lines ğŸ“¥
        uses: ./.github/actions/download-manifests
        with:
          hist-line-dir: /tmp/jupyter/hist_lines/
          manifest-dir: /tmp/jupyter/manifests/
          fast-build: ${{ contains(github.event.pull_request.title, '[FAST_BUILD]') }}
      - name: Display structure of downloaded files ğŸ”ï¸
        run: |
          ls -R /tmp/jupyter/hist_lines/
          ls -R /tmp/jupyter/manifests/
        shell: bash

      - name: Checkout Wiki Repo ğŸ“ƒ
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}.wiki
          path: wiki/

      - name: Update wiki ğŸ·
        run: python3 -m tagging.update_wiki --wiki-dir wiki/ --hist-line-dir /tmp/jupyter/hist_lines/ --manifest-dir /tmp/jupyter/manifests/
        shell: bash

      - name: Push Wiki to GitHub ğŸ“¤
        if: env.PUSH_TO_REGISTRY == 'true'
        uses: stefanzweifel/git-auto-commit-action@8756aa072ef5b4a080af5dc8fef36c5d586e521d # v5.0.0
        with:
          commit_message: "Automated wiki publish for ${{ github.sha }}"
          repository: wiki/
