name: Download build history lines and manifests from GitHub artifacts and push them to the GitHub wiki
# We're doing everything in one workflow on purpose
# This way we make sure we don't access wiki pages from several jobs simultaneously

env:
  PUSH_TO_REGISTRY: ${{ github.ref == 'refs/heads/main' || github.event_name == 'schedule' }}

on:
  workflow_call:

permissions:
  contents: write

jobs:
  wiki-update:
    runs-on: ubuntu-24.04
    timeout-minutes: 1

    steps:
      - name: Checkout Repo âš¡ï¸
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0
      - name: Create dev environment ğŸ“¦
        uses: ./.github/actions/create-dev-env

      - name: Download all history lines ğŸ“¥
        uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6.0.0
        with:
          pattern: "*-history_line"
          path: /tmp/jupyter/hist_lines/

      - name: Download all manifests ğŸ“¥
        uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6.0.0
        with:
          pattern: "*-manifest"
          path: /tmp/jupyter/manifests/

      - name: Checkout Wiki Repo ğŸ“ƒ
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          repository: ${{ github.repository }}.wiki
          path: wiki_src/

      - name: Update wiki ğŸ·
        run: |
          python3 -m wiki.update_wiki \
            --wiki-dir wiki_src/ \
            --hist-lines-dir /tmp/jupyter/hist_lines/ \
            --manifests-dir /tmp/jupyter/manifests/ \
            --repository ${{ github.repository }}
        shell: bash

      - name: Push Wiki to GitHub ğŸ“¤
        if: env.PUSH_TO_REGISTRY == 'true'
        uses: stefanzweifel/git-auto-commit-action@28e16e81777b558cc906c8750092100bbb34c5e3 # v7.0.0
        with:
          commit_message: "Automated wiki publish for ${{ github.sha }}"
          repository: wiki_src/
