name: Download build manifests from GitHub artifacts and push them to GitHub wiki
# We're doing everything in one workflow on purpose
# This way we make sure we don't access wiki pages from several jobs simultaneously

env:
  PUSH_TO_REGISTRY: ${{ (github.repository_owner == 'jupyter' || github.repository_owner == 'mathbunnyru') && (github.ref == 'refs/heads/main' || github.event_name == 'schedule') }}

on:
  workflow_call:

jobs:
  wiki-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo âš¡ï¸
        uses: actions/checkout@v4
      - name: Create dev environment ğŸ“¦
        uses: ./.github/actions/create-dev-env

      - name: Download all history lines ğŸ“¥
        uses: actions/download-artifact@v4
        with:
          pattern: "*-history_line"
          path: /tmp/jupyter/hist_lines/

      - name: Download all manifests ğŸ“¥
        uses: actions/download-artifact@v4
        with:
          pattern: "*-manifest"
          path: /tmp/jupyter/manifests/

      - name: Checkout Wiki Repo ğŸ“ƒ
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}.wiki
          path: wiki/

      - name: Update wiki ğŸ·
        run: python3 -m tagging.update_wiki --wiki-dir wiki/ --hist-lines-dir /tmp/jupyter/hist_lines/ --manifests-dir /tmp/jupyter/manifests/
        shell: bash

      - name: Push Wiki to GitHub ğŸ“¤
        if: env.PUSH_TO_REGISTRY == 'true'
        uses: stefanzweifel/git-auto-commit-action@8621497c8c39c72f3e2a999a26b4ca1b5058a842 # v5.0.1
        with:
          commit_message: "Automated wiki publish for ${{ github.sha }}"
          repository: wiki/
