name: Update dockerhub overviews

env:
  OWNER: ${{ github.repository_owner }}

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/hub-overview.yml"

      - "all-spark-notebook/README.md"
      - "base-notebook/README.md"
      - "datascience-notebook/README.md"
      - "minimal-notebook/README.md"
      - "pyspark-notebook/README.md"
      - "r-notebook/README.md"
      - "scipy-notebook/README.md"
      - "tensorflow-notebook/README.md"

jobs:
  update-dockerhub-overview:
    name: Update dockerhub overviews
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - image: base-notebook
            description: "Small base image for Jupyter Notebook stacks from https://github.com/jupyter/docker-stacks"
          - image: minimal-notebook
            description: "Minimal Jupyter Notebook Python Stack from https://github.com/jupyter/docker-stacks"
          - image: scipy-notebook
            description: "Scientific Jupyter Notebook Python Stack from https://github.com/jupyter/docker-stacks"
          - image: r-notebook
            description: "R Jupyter Notebook Stack from https://github.com/jupyter/docker-stacks"
          - image: tensorflow-notebook
            description: "Scientific Jupyter Notebook Python Stack w/ TensorFlow from https://github.com/jupyter/docker-stacks"
          - image: datascience-notebook
            description: "Data Science Jupyter Notebook Python Stack from https://github.com/jupyter/docker-stacks"
          - image: pyspark-notebook
            description: "Python and Spark Jupyter Notebook Stack from https://github.com/jupyter/docker-stacks"
          - image: all-spark-notebook
            description: "Python, Scala, R and Spark Jupyter Notebook Stack from https://github.com/jupyter/docker-stacks"

    steps:
      - name: Checkout Repo ‚ö°Ô∏è
        uses: actions/checkout@v3

      - name: Push README to Dockerhub üê≥
        uses: christian-korneck/update-container-description-action@d36005551adeaba9698d8d67a296bd16fa91f8e8 # v1
        env:
          DOCKER_USER: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASS: ${{ secrets.DOCKERHUB_TOKEN }}
        with:
          destination_container_repo: ${{ env.OWNER }}/${{ matrix.image }}
          provider: dockerhub
          short_description: ${{ matrix.description }}
          readme_file: ${{ matrix.image }}/README.md
