name: Build Sphinx Documentation and check links

on:
  schedule:
    # Weekly, at 03:00 on Monday UTC time
    - cron: "0 3 * * 1"
  pull_request:
    paths:
      - ".github/workflows/sphinx.yml"

      - "docs/**"
      - "README.md"
      - ".readthedocs.yaml"
      - "requirements-docs.txt"
  push:
    branches:
      - main
      - master
    paths:
      - ".github/workflows/sphinx.yml"

      - "docs/**"
      - "README.md"
      - ".readthedocs.yaml"
      - "requirements-docs.txt"
  workflow_dispatch:

jobs:
  build-docs:
    name: Build Sphinx Documentation
    if: github.event_name != 'schedule' || (github.event_name == 'schedule' && github.repository == 'jupyter/docker-stacks')
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repo âš¡ï¸
        uses: actions/checkout@v3

      - name: Set Up Python ğŸ
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install Doc Dependencies ğŸ“¦
        run: |
          pip install --upgrade pip
          pip install -r requirements-docs.txt

      - name: Build Documentation ğŸ“–
        run: make docs

      - name: Check Documentation URLs ğŸ”—
        run: make linkcheck-docs
