name: Build Sphinx Documentation

on:
  pull_request:
    paths:
      - ".github/workflows/sphinx.yml"

      - "docs/**"
      - ".readthedocs.yaml"
      - "requirements-dev.txt"
  push:
    branches:
      - main
      - master
    paths:
      - ".github/workflows/sphinx.yml"

      - "docs/**"
      - ".readthedocs.yaml"
      - "requirements-dev.txt"

jobs:
  build-docs:
    name: Build Sphinx Documentation
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install Dev Dependencies
        run: |
          python -m pip install --upgrade pip
          make dev-env

      - name: Build Documentation
        run: make docs

      - name: Extract Source Strings
        working-directory: docs
        run: |
          sphinx-build -M gettext ./ ./_build/
          sphinx-intl update -p ./_build/gettext -l en

      - name: Push Strings to Master
        if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'
        uses: stefanzweifel/git-auto-commit-action@abd87b7d94702070bef78dc1d56b6928b8fa9ecc # dependabot updates to latest release
        with:
          commit_message: "Automated publish for ${{github.sha}}"
