name: Build Sphinx Documentation and check links

on:
  schedule:
    # Weekly, at 03:00 on Monday UTC
    - cron: "0 3 * * 1"
  pull_request:
    paths:
      - ".github/workflows/sphinx.yml"
      - "Makefile"

      - "docs/**"

      # These files are also rendered as docs pages
      - "README.md"
      - "CHANGELOG.md"

      # These files are used to generate some code snippets in the docs
      - "tagging/manifests/apt_packages.py"
      - "tagging/manifests/manifest_interface.py"
      - "tagging/taggers/sha.py"
      - "tagging/taggers/tagger_interface.py"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/sphinx.yml"
      - "Makefile"

      - "docs/**"

      - "README.md"
      - "CHANGELOG.md"

      - "tagging/manifests/apt_packages.py"
      - "tagging/manifests/manifest_interface.py"
      - "tagging/taggers/sha.py"
      - "tagging/taggers/tagger_interface.py"
  workflow_dispatch:

jobs:
  build-docs:
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    if: github.repository_owner == 'jupyter' || github.repository_owner == 'mathbunnyru' || github.event_name != 'schedule'

    steps:
      - name: Checkout Repo ‚ö°Ô∏è
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Set Up Python üêç
        uses: actions/setup-python@v6
        with:
          python-version: 3.12

      - name: Install Doc Dependencies üì¶
        run: |
          pip install --upgrade pip
          pip install --upgrade -r docs/requirements.txt

      - name: Build Documentation üìñ
        run: make docs

      - name: Check Documentation URLs üîó
        run: make linkcheck-docs || make linkcheck-docs
