name: Build Sphinx Documentation and check links

on:
  schedule:
    # Weekly, at 03:00 on Monday UTC time
    - cron: "0 3 * * 1"
  pull_request:
    paths:
      - ".github/workflows/sphinx.yml"

      - "docs/**"
      - "README.md"
      - ".readthedocs.yaml"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/sphinx.yml"

      - "docs/**"
      - "README.md"
      - ".readthedocs.yaml"
  workflow_dispatch:

jobs:
  build-docs:
    permissions:
      contents: write
    if: github.repository_owner == 'jupyter' || github.repository_owner == 'mathbunnyru' || github.event_name != 'schedule'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo âš¡ï¸
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set Up Python ğŸ
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install Doc Dependencies ğŸ“¦
        run: |
          pip install --upgrade pip
          pip install --upgrade -r docs/requirements.txt

      - name: Build Documentation ğŸ“–
        run: make docs

      - name: Check Documentation URLs ğŸ”—
        run: make linkcheck-docs || make linkcheck-docs
