name: Download image artifact from GitHub artifacts and test it

on:
  workflow_call:
    inputs:
      imageName:
        description: "Image name to be tested"
        required: true
        type: string
      platform:
        description: "Target platform for the built image"
        required: true
        type: choice
        options:
          - amd64
          - arm64

jobs:
  test-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo âš¡ï¸
        uses: actions/checkout@v3
      - name: Create dev environment ğŸ“¦
        uses: ./.github/actions/create-dev-env

      - name: Download built image ğŸ“¥
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.imageName }}-${{ inputs.platform }}
          path: /tmp/
      - name: Load downloaded image to docker ğŸ“¥
        run: |
          docker load --input /tmp/${{ inputs.imageName }}-${{ inputs.platform }}.tar
          docker image ls -a
        shell: bash

      - name: Run tests âœ…
        run: python3 -m tests.run_tests --short-image-name ${{ inputs.imageName }}
        shell: bash
