name: Download image artifact from GitHub artifacts, tag it and push to DockerHub

on:
  workflow_call:
    inputs:
      images:
        description: "Stringified JSON object listing image names"
        required: true
        type: string
      platform:
        description: "Image platform"
        required: true
        type: string
      runsOn:
        description: "GitHub Actions Runner image"
        required: true
        type: string

jobs:
  tag-push-images:
    runs-on: ${{ inputs.runsOn }}

    strategy:
      matrix:
        image: ${{fromJson(inputs.images)}}

    steps:
      - name: Checkout Repo âš¡ï¸
        uses: actions/checkout@v3
      - name: Create dev environment ğŸ“¦
        uses: ./.github/actions/create-dev-env

      - name: Download built image ğŸ“¥
        uses: ./.github/actions/load-image
        with:
          image: ${{ matrix.image }}
          platform: ${{ inputs.platform }}

      - name: Create tags ğŸ·
        run: python3 -m tagging.tag_image --short-image-name ${{ matrix.image }}
        shell: bash

      - name: Login to Docker Hub ğŸ”
        if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main' || github.event_name == 'schedule'
        uses: docker/login-action@49ed152c8eca782a232dede0303416e8f356c37b # dependabot updates to latest release
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Images to Docker Hub ğŸ“¤
        if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main' || github.event_name == 'schedule'
        run: docker push --all-tags jupyter/${{ matrix.image }}
        shell: bash
