name: Download parent image, build new one, upload it to GitHub artifacts

on:
  workflow_call:
    inputs:
      parentImage:
        description: "Parent image name"
        required: true
        type: string
      image:
        description: "Image name"
        required: true
        type: string
      platform:
        description: "Image platform"
        required: true
        type: string
      runsOn:
        description: "GitHub Actions Runner image"
        required: true
        type: string

jobs:
  build-push-image:
    runs-on: ${{ inputs.runsOn }}
    steps:
      - name: Checkout Repo âš¡ï¸
        uses: actions/checkout@v3
      - name: Create dev environment ğŸ“¦
        uses: ./.github/actions/create-dev-env

      - name: Download parent built image ğŸ“¥
        if: ${{ inputs.parentImage != '' }}
        uses: ./.github/actions/load-image
        with:
          image: ${{ inputs.parentImage }}
          platform: ${{ inputs.platform }}

      - name: Build image ğŸ› 
        working-directory: ${{ inputs.image }}
        run: docker build --tag jupyter/${{ inputs.image }} --tag jupyter/${{ inputs.image }} .
        env:
          DOCKER_BUILDKIT: 1
          # Full logs for CI build
          BUILDKIT_PROGRESS: plain
        shell: bash
      - name: Save image as a file ğŸ’¾
        run: docker save jupyter/${{ inputs.image }} -o /tmp/${{ inputs.image }}-${{ inputs.platform }}.tar
        shell: bash

      - name: Upload artifact ğŸ’¾
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.image }}-${{ inputs.platform }}
          path: /tmp/${{ inputs.image }}-${{ inputs.platform }}.tar
